x-versia: &versia-default
  build: .
  env_file: [ .env, .env.local ]
  depends_on:
    - nats

services:
  #  db:
  #    image: postgres:16.2-alpine
  #    environment:
  #      POSTGRES_DB: postgres
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #    ports:
  #      - "5432:5432"

  nats:
    image: nats:2.9.25-scratch
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--js"

  versia-1:
    <<: *versia-default
    hostname: versia.localhost
    volumes:
      - type: bind
        source: ./1.db
        target: /app/test.db
    environment:
      VERSIA_PORT: 8080
      VERSIA_INSTANCE_ADDRESS: http://versia.localhost:8080
      NATS_URI: nats://nats:4222
      NATS_STREAM_NAME: versia-go
    ports:
      - "8080:8080"
