apiVersion: v1
kind: Service
metadata:
  name: {{ include "versiago.fullname" . }}
  labels:
    {{- include "versiago.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "versiago.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
